### ISSUE TITLE
libgit2 but in Git::Raw that breaks compatability with latest version of GitLab

### ISSUE THREAD

**Issue by nneul** [jacquesg/p5-Git-Raw#164]
GitLab devs have already worked around in their code:

https://gitlab.com/gitlab-org/gitlab-ce/issues/3265#note_2527976
https://gitlab.com/gitlab-org/gitlab-workhorse/merge_requests/2

but the underlying bug is still present in Git::Raw version of libgit2 - basically it should be using case insensitive comparison on the 'WWW-Authenticate' header so that it still works with a server returning 'Www-Authenticate'.

Here's the upstream commit that fixes libgit2:

https://github.com/libgit2/libgit2/commit/31a76374a9bea7d61fec3741d46f09872a8bbb2a

Please refresh or cherry-pick that fix so it's included in next CPAN version.

**Comment by jacquesg** [comment]
I've been working on updating the underlying libgit2 version. Problem is that I've not finished the documentation yet due to the number of breaking changes.

Next release will include the fix.

**Comment by jacquesg** [comment]
This one should be fixed in ```0.58```. Thanks for the report.
