### ISSUE TITLE
`git_revparse_single()` isn't exposed

### ISSUE THREAD

**Issue by jeffstyr** [jacquesg/p5-Git-Raw#167]
It doesn't seem that the functionality of `git_revparse_single()` is available anywhere; it's used to find an object using any of the various formats that git allows for specifying revisions (e.g, "abc123^^", "v0.1.0:foo/bar/baz.c", "HEAD^{commit}", "some_branch").

See its [documentation](http://libgit2.github.com/libgit2/#HEAD/group/revparse/git_revparse_single), and several examples of its usage here: http://libgit2.github.com/docs/guides/101-samples/

This would be handy to have.

**Comment by jacquesg** [comment]
I've actually started working on this quite some time ago, just never finished it. Will see what I can do.

https://github.com/jacquesg/p5-Git-Raw/commits/jacquesg/revparse

**Comment by jeffstyr** [comment]
Oh excellent--thanks much. I haven't done any XS programming so it would have taken me a while to figure out.

**Comment by jacquesg** [comment]
The functionality was added in #124.

**Comment by jeffstyr** [comment]
Thanks much!
