### ISSUE TITLE
clear_refspecs() is documented in Git::Raw::Remote, but missing in .xs

### ISSUE THREAD

**Issue by ssinyagin** [jacquesg/p5-Git-Raw#169]
The POD for  Git::Raw::Remote lists clear_refspecs(), but this function is not implemented in XS.

**Comment by ssinyagin** [comment]
as a result, I cannot remove a generic * refspec and replace it with the one that fetches only one branch

**Comment by jacquesg** [comment]
These functions have been removed by libgit2, heres the excerpt from the Changelog:

* `git_remote_save()` and `git_remote_clear_refspecs()` have been
  removed. Remote's configuration is changed via the configuration
  directly or through a convenience function which performs changes to
  the configuration directly.

I'll remove it from the POD.

**Comment by jacquesg** [comment]
Thanks for the report.
