### ISSUE TITLE
 Git::Raw::Repository->merge(): wrong return results in POD

### ISSUE THREAD

**Issue by ssinyagin** [jacquesg/p5-Git-Raw#170]
hi again

in POD,  Git::Raw::Repository->merge() is described to return a hash. In XS, it returns nothing.

**Comment by jacquesg** [comment]
Indeed. I'll give this a once-over.

**Comment by jacquesg** [comment]
Fixed in f7a83cbd88321cc82b2e06df4e65f4ddc4ca1640, thank for the report.
