### ISSUE TITLE
add_frombuffer() in Git::Raw::Index should return an Entry object

### ISSUE THREAD

**Issue by ssinyagin** [jacquesg/p5-Git-Raw#180]
`git_index_add_frombuffer()` in `libgit2` updates the entry with the blob ID. Please make the corresponding method in `Git::Raw::Index` return a `Git::Raw::Index::Entry` object.

Use case: after calling `add_frombuffer()`, I can compare the blob ID with the previous value, and immediately derive if the data file was changed.

**Comment by jacquesg** [comment]
Fixed in 14ce0c30183fe30ab074b1d2b979a95d2c1421db
