### ISSUE TITLE
add_frombuffer() in Git::Raw::Index should accept string reference

### ISSUE THREAD

**Issue by ssinyagin** [jacquesg/p5-Git-Raw#181]
add_frombuffer() in Git::Raw::Index accepts only a string for the new blob content. The string may be quite large, and it's beneficial to pass a string reference. Currently add_frombuffer() segfaults if I pass a reference instead of string.

**Comment by jacquesg** [comment]
Fixed in 767438b2b315863eb3343d8e6eed10e6ce04c29b
