### ISSUE TITLE
exact_match_only is not documented in Git::Raw::Repository->diff()

### ISSUE THREAD

**Issue by ssinyagin** [jacquesg/p5-Git-Raw#182]
The flag `exact_match_only` is not listed in POD for Git::Raw::Repository->diff()

The following code generates a diff based on SHA checksums mismatch only:

```
    my $diff = $old_tree->diff(
        {'tree' => $new_tree,
         'flags' => {
             'exact_match_only' => 1,
         },
        });
```

**Comment by jacquesg** [comment]
```exact_match_only``` is a flag to ```find_similar()```. The above should really be

```
my $diff = $old_tree->diff({'tree' => $new_tree});
$diff->find_similar({'flags' => {'exact_match_only' => 1}});
```

**Comment by jacquesg** [comment]
The documentation for the flag is here :)

https://github.com/jacquesg/p5-Git-Raw/blob/master/lib/Git/Raw/Diff.pm#L100
