### ISSUE TITLE
Git::Raw::Tree::Entry  needs is_object_blob() and is_object_tree() methods

### ISSUE THREAD

**Issue by ssinyagin** [jacquesg/p5-Git-Raw#183]
There is already `file_mode()` method, but it's not convenient, and it returns different filemodes for executables and normal files.

`libgit2` has a call `git_tree_entry_type` which retrieves a constant indicating that the entry is a tree, a blob, or a commit. So, corresponding Perl method could be `is_object_blob()` and `is_object_tree()`, and also probably `is_object_commit()`, although I don't know a useful scenario for it.

The motivation is, that I need to traverse tree contents recursively, and I'm only interested in entry names and types, so reading the object content would be an overkill. But currently the only way to know the type of the entry is to either use `file_mode`, or to read the object from ODB.

**Comment by jacquesg** [comment]
Fixed by 6a1a3fd78d9bafbd5a44f27fb60f08dba2e279ed. Added a ```type``` method to the ```Git::Raw::Tree::Entry```.
