### ISSUE TITLE
POD misleading in Git::Raw::Tree::Entry 

### ISSUE THREAD

**Issue by ssinyagin** [jacquesg/p5-Git-Raw#184]
hi Jacques,

in POD for Git::Raw::Tree::Entry, the id() method is not explained correctly. The correct description is given in libgit2 API:
`Get the id of the object pointed by the entry`

**Comment by jacquesg** [comment]
Thanks fixed in fd4cacd1d667fbfadf1f14bda28e23944ff5b6d7
