### ISSUE TITLE
Add support for git_odb_foreach

### ISSUE THREAD

**Issue by book** [jacquesg/p5-Git-Raw#185]
I'm trying to get the list of all digests in a repository (and their object type) using Git::Raw. Basically, it would be the equivalent of `git cat-file --batch-check --batch-all-objects`.

As you told me, it should be doable using `git_odb_foreach`. So I'm opening an issue to request this functionality in Git::Raw::Odb.

Thanks,

**Comment by jacquesg** [comment]
Added in da59b1af68c78ce80bfa9aff5faa1ee413efcf67 and ffa2437a8ed996b5c0e6f50ec497b565d5b6c237. Can you verify that these changes are sufficient?

**Comment by book** [comment]
Here are my various attempts, that mostly produced the expected results:

    $ perl -MGit::Raw -E 'Git::Raw::Repository->open(".")->odb->foreach( sub { say $_[0]; return } )'
    cc5c34f14d06c688b259a884f15b50f3643f5579
    ...

And with a slightly longer callback:

    $ perl -MGit::Raw -E '
        my $r = Git::Raw::Repository->open(".");
        my @type = qw( bad commit tree blob tag );
        $r->odb->foreach( sub { my $id=shift; my $o = Git::Raw::Object->lookup( $r, $id ); say "$id $type[$o->type]"; return; } );
    ' 
    cc5c34f14d06c688b259a884f15b50f3643f5579 commit
    ...

However, the following code produced an error:

    $ perl -Mblib -MGit::Raw -E '
        my $r = Git::Raw::Repository->open(".");
        my @type = qw( bad commit tree blob tag );
        $r->odb->foreach( sub { my $id=shift; my $o = Git::Raw::Object->lookup( $r, $id ); say $o->id, " ", $type[$o->type]; return; } );
    '
    git_pack_foreach_entry callback returned -1

Wrapping the code in an `eval` block an printing the value of `$@` gave:

    id is not a valid Git::Raw::Object macro

which sounded like something I could do.

**Comment by jacquesg** [comment]
You need to return ```0``` in the callback. A ```Git::Raw::Object``` does not currently have an ```id```, but I'll add it.

**Comment by jacquesg** [comment]
Adding ```id``` in #186

**Comment by jacquesg** [comment]
5c114d906b9f68ed5c7e59a4a81c09b9287084cf add ```id```

**Comment by book** [comment]
It would also be useful to provide `size`, if it's easily available from the odb.

**Comment by jacquesg** [comment]
This isn't readily available nor do I think it makes sense. What you need I think is

```
if ($o->type == Git::Raw::Object->BLOB)
{
  my $blob = Git::Raw::Blob->lookup ($repo, $o->id);
  my $size = $blob->size;
  my $content = $blob->content;
}
```

**Comment by book** [comment]
`size` and `content` only exist for `Git::Raw::Blob`, but in the git object database, all object types have a size (and a raw content):

    $ git cat-file --batch-check --batch-all-objects | head
    0006f34f06abb6f95a27605053db1e48a196d822 tree 2253
    0007c41dbca36ec635ab3db392e9fca005b44286 blob 49286
    000d754d2f377fd7c21178aa74be1771baf17171 blob 2880
    0018ebbf047d549ee2c8ad6cb8a6dc66540a97a5 blob 1190
    001eb6d871742b6f41cb296e57d69d9a6e041db6 commit 255
    0020a7762899f84ce5d54a7f2bc58a354c62bc2a blob 8497
    0023f95ffdc839888f5d9b9a9d54fd7de15ada15 blob 17660
    0029c27da0fbcad9ff8b0959bd05d96e72ebced4 tag 147
    002a59d751d49a2e5f8ccd4b93cebf172f7e9100 tree 304
    002ce43f5a437c432c9216b6d009bb015b6d303f tree 34

**Comment by book** [comment]
Also, I was wondering why `Git::Raw::Object->lookup` didn't return a Perl obect of the right specialized class, instead of the generic (parent?) class.

**Comment by jacquesg** [comment]
```Git::Raw::Repository->lookup``` will return the specialized object.

**Comment by jacquesg** [comment]
There does seem to be a way to get the actual size (https://libgit2.github.com/libgit2/#HEAD/group/odb/git_odb_read).

This would require me to add a ``Git::Raw::Odb::Object```

**Comment by jacquesg** [comment]
Can you try 61b9a50fa3c5d837ee2f2a4a4aeb86a916b599ff

**Comment by book** [comment]
Works perfectly! Thanks!

Does the `Git::Raw::Odb::Object` also give access to the raw object data?
(I assume this is <https://libgit2.github.com/libgit2/#HEAD/group/odb/git_odb_object_data>).

**Comment by jacquesg** [comment]
Added (45a4b89de1091cae2c9351dff4b24ada30df3c9c)

**Comment by book** [comment]
`data` works fine, thanks.

**Comment by book** [comment]
I noted that `read` in `Git::Raw::Odb` does not work with abbreviated digests. Having the same behaviour as `lookup` in `Git::Raw::Repositoy` would be nice.

**Comment by jacquesg** [comment]
Fixed (b155b909988160a1b0f38eecf43a93a34c6a7fc8)

**Comment by book** [comment]
Thanks!

However, this last patch has an issue, when trying to obtain ambiguous digests:

    $ git cat-file --batch-check --batch-all-objects
    577ecc210a55a5da10552a4415c4cbb5e321039b blob 988
    577eccaacd6343158463f9eaefa19dec78358437 blob 224
    65237d4ff8bddefebb2d4801e796f94fa9a9bbeb tree 66
    9f0363e979a368db9748fb93278ab91a2152aa71 commit 255
    $ perl -MGit::Raw -le '$r=Git::Raw::Repository->open(".");print $r->lookup(shift)' 577ecc
    Ambiguous SHA1 prefix - found multiple offsets for pack entry at -e line 1
    $ perl -MGit::Raw -le '$r=Git::Raw::Repository->open(".");print $r->odb->read(shift)' 577ecc
    Git::Raw::Odb::Object=SCALAR(0x55af77bdeb30)
    Segmentation fault

**Comment by jacquesg** [comment]
Yep, I missed a line :(

**Comment by jacquesg** [comment]
Fixed (fa99da888abb3fbe7e85323cac6449faf4d11e26)

**Comment by book** [comment]
Everything works perfectly now! Thanks for being so reactive.

I'll now wait for the next release. `:-)`

**Comment by jacquesg** [comment]
I'll create a release within the next few minutes

**Comment by jacquesg** [comment]
https://metacpan.org/release/JACQUESG/Git-Raw-0.73
