### ISSUE TITLE
Add support for git_odb_write (and git_odb_hash)

### ISSUE THREAD

**Issue by book** [jacquesg/p5-Git-Raw#187]
To complete the `Git::Raw` backend I'm currently writing for [Git::Database](https://metacpan.org/release/Git-Database), I need to implement the `put_object` method for the [Git::Database::Role::ObjectWriter](https://metacpan.org/pod/Git::Database::Role::ObjectWriter) role.

[git_odb_write](https://libgit2.github.com/libgit2/#HEAD/group/odb/git_odb_write) looks like the method that I 
need.

If I want to improve on the default implementation of `[hash_object]`, I could probably make use [git_odb_hash](https://libgit2.github.com/libgit2/#HEAD/group/odb/git_odb_hash) too.

Thanks in advance.

**Comment by jacquesg** [comment]
Added in f3e288b1a19c71af9250934d6a5037372f4cdf64. Let me know if you require a new release.

**Comment by book** [comment]
Excellent! Thanks a lot, with your last patch, `Git::Raw` is a fully supported backend for `Git::Database`.

I'll make your next release the minimum required version.

**Comment by jacquesg** [comment]
https://metacpan.org/release/JACQUESG/Git-Raw-0.74
