### ISSUE TITLE
Should seamlessly use system libs instead of convenience copies

### ISSUE THREAD

**Issue by Zugschlus** [jacquesg/p5-Git-Raw#195]
Hi,

in deps, there is a number of "external" libraries included that an average LInux system already has. In Debian, we take special consideration not to use "convenience copies" of libraries that upstreams bundle with their software releases. This especially applies to libz, which needs security updates quite often.

The build process of Git::Raw should detect that the system has those libs installed as system packages and use those instead of the local convenience copies. The build-process should, in this case, still complete when one zaps the entire deps directory.

The following patch makes this behavior hard-coded, but removes all usage of the convenience libs, so "your" version should be a bit smarter than this, sledge-hammer approach.

```
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -250,12 +250,7 @@ if ($Config{usethreads} && !$is_sunpro)
 my @deps = glob 'deps/libgit2/deps/{http-parser,zlib}/*.c';
 my @srcs = glob 'deps/libgit2/src/{*.c,transports/*.c,xdiff/*.c,streams/*.c}';
 
-if ($is_msvc) {
-       push @srcs, 'deps/libgit2/src/hash/hash_win32.c';
-}
-elsif (!$library_opts{'ssl'}{'use'} && !$is_osx) {
-       push @srcs, 'deps/libgit2/src/hash/hash_generic.c';
-}
+$lib .= ' -lgit2';
 
 # the system regex is broken on Solaris, not available on Windows
 if ($is_windows || $is_solaris) {
@@ -333,7 +328,7 @@ my %WriteMakefileArgs = (
     "Getopt::Long" => "2.35"
   },
   "DISTNAME" => "Git-Raw",
-  "INC" => "-I. -Ideps/libgit2 -Ideps/libgit2/src -Ideps/libgit2/include -Ideps/libgit2/deps/http-parser -Ideps/libgit2/deps/zlib",
+  "INC" => "-I. ",
   "LICENSE" => "perl",
   "MIN_PERL_VERSION" => "5.006",
   "NAME" => "Git::Raw",
```

**Comment by jacquesg** [comment]
This distribution was designed to ship a compatible copy of libgit2 and build that. libgit2 is not have a stable API so relying on the ones in installed by some OS vendor is not going always going to work.

**Comment by Zugschlus** [comment]
Thanks for your consideration. You now have a patched version in Debian.
