### ISSUE TITLE
Add support for commit trailers

### ISSUE THREAD

**Issue by bk2204** [jacquesg/p5-Git-Raw#197]
Recent versions of libgit2 offer support for commit message trailers, such as Signed-off-by.  It would be great if these interfaces could be exposed through Git::Raw, so that it isn't necessary to shell out to `git interpret-trailers`.

Ideally, the implementation would support multiple trailers of the same type gracefully (e.g., multiple "Cc" trailers).

**Comment by jacquesg** [comment]
That seems reasonable, let me see what I can do.

**Comment by jacquesg** [comment]
Added in #198. Let me know if this works for you.

**Comment by bk2204** [comment]
This works great, thanks.

**Comment by jacquesg** [comment]
You're welcome. I'll be releasing a new version to CPAN soon.
