### ISSUE TITLE
-m32 option makes build fail on most 32 bit arches

### ISSUE THREAD

**Issue by Zugschlus** [jacquesg/p5-Git-Raw#199]
Hi,

in Debian, the compiler of most 32 bit arches (including mips, mipsel, m68k, hppa) does not have the -m32 option. The build this unconditionally fails on those arches.

Since Debian doesn't need that hack (we do things right on 64 bit arches), I have removed the option in the Debian package completely (and do hope that I didn't introduce other breakage by doing that).

Please consider being less generous with the -m32 option and only add it on arches where it is actually needed. The current method of checking for the ptrsize and then excluding arm hurts non-arm 32 bit arches.

Greetings
Marc

**Comment by jacquesg** [comment]
Pull requests welcome.

**Comment by waterkip** [comment]
The patch can be found here: https://salsa.debian.org/perl-team/modules/packages/libgit-raw-perl/blob/2e7d438d4e4dedde20e0909723636b48aa60ee75/debian/patches/remove-m32

**Comment by jacquesg** [comment]
The patch is insufficient. A better mechanism is needed to detect a multilib gcc installation, and add ```-m32``` for these scenarios.

**Comment by jacquesg** [comment]
Closing this seeing that there hasn't been any activity.
