### ISSUE TITLE
Provide Makefile.PL / cpanfile in git repo

### ISSUE THREAD

**Issue by waterkip** [jacquesg/p5-Git-Raw#208]
Hello, 

testing and building Git::Raw takes a while because `dzil test` copies/build the gitlib2 sources and seems to connect to the internet before actually testing (`[@Author::ALEXBIO/@GitHub/GitHub::Meta] Getting GitHub repository info`). It would be nice if contributors could test their changes quicker without having to rebuild everything on each change.

**Comment by jacquesg** [comment]
Agreed. I have found that using ccache makes this significantly more bearable. You could also revert 1b32c6758d20091be5860b8e83525ec14e13a041 and then use ```make -jX``` to speed up the process.

**Comment by waterkip** [comment]
I can have a go at Dzil to provide a Makefile.PL and a cpanfile after a build. Would that be accepted?
And perhaps use Docker/Docker Compose, that could also speed up tests a bit if you mount the correct things.

**Comment by jacquesg** [comment]
Wouldn't got all the way to docker. If anything, I should probably create my ```PluginBundle```.
