### ISSUE TITLE
Request: support enumeration and traversal of submodules

### ISSUE THREAD

**Issue by cxw42** [jacquesg/p5-Git-Raw#210]
Thank you for this module, which I am using in a forthcoming project.  I would like to be able to enumerate and traverse submodules.  Would you be willing to add support for at least [`git_submodule_foreach`](https://libgit2.org/libgit2/#HEAD/group/submodule/git_submodule_foreach) and [`git_submodule_open`](https://libgit2.org/libgit2/#HEAD/group/submodule/git_submodule_open)?  Thank you for considering this request!

(Related to #192, but reading rather than creating.)

**Comment by jacquesg** [comment]
Let me see what I can do.

**Comment by jacquesg** [comment]
https://github.com/jacquesg/p5-Git-Raw/tree/submodule has a work-in-progress version, could you test and see if it works for you?

**Comment by cxw42** [comment]
Thank you for the quick response!  It looks good in my initial tests :) .

**Comment by jacquesg** [comment]
Fixed by #212

**Comment by cxw42** [comment]
@jacquesg Would you be willing to release a CPAN version with this change?  It is working well for me and I would like to be able to specify it as a regular dependency so my project can be installed via cpanm.  Thanks!

**Comment by jacquesg** [comment]
Version 0.84 should be on CPAN shortly.
