### ISSUE TITLE
Refspec issue with patterns,

### ISSUE THREAD

**Issue by EvanCarroll** [jacquesg/p5-Git-Raw#213]
With git you can provide a refspec like,

```
[remote "upstream"]
        url = ssh://git@co:7999/co/co-whm.git
        fetch = +refs/heads/8*:refs/remotes/upstream/8*
```

However it seems that `Git::Raw` doesn't support refpsecs with patterns. I get the error [`+refs/heads/8:refs/remotes/upstream/8' ` is not a valid refpsec](https://github.com/jacquesg/p5-Git-Raw/blob/313b4127ba96c998f8df93543b580c3583fb505b/deps/libgit2/src/refspec.c#L147),

**Comment by jacquesg** [comment]
I believe this may be addressed when I've finally managed to upgrade the copy of libgit2 again. If you're on a Unix machine, can you try https://github.com/jacquesg/p5-Git-Raw/tree/update-libgit2?

I need to do some work to get PCRE to compile on Windows before I can merge it.

**Comment by jacquesg** [comment]
Does the latest version on CPAN fix this for you?

**Comment by EvanCarroll** [comment]
Not sure, don't use this anymore and super busy now. Realistically I won't be able to retest it for a long time. I wouldn't hold open this issue for me.

**Comment by EvanCarroll** [comment]
Looping back around, got this problem again about to try a newer version. Notes to me.


```
use Git::Raw::Remote;
use Git::Raw::Repository;
my $repo = Git::Raw::Repository->open("/usr/local/myrepo");
print Git::Raw::Remote->load( $repo, 'upstream' ) . "\n";
```
