### ISSUE TITLE
libssh2 deprecated in Redhat 7

### ISSUE THREAD

**Issue by toddr** [jacquesg/p5-Git-Raw#214]
I just thought I'd give you a heads up. libssh2-devel is no longer available in Redhat 8. Per Redhat: 

https://bugzilla.redhat.com/show_bug.cgi?id=1660344

> Long story short, libssh2 has been removed from RHEL-8 intentionally.
> 
> libssh is now the supported SSH library in RHEL-8.  It has incompatible ABI/API with libssh2, so libssh2-based application needs to be migrated to libssh unless they support both the libraries (as, for example upstream curl does).

I don't know what other distros are doing but you might consider if switching to libssh might be desirable in the near term.

**Comment by jacquesg** [comment]
libssh2 is a requirement of libgit2, I believe there are some plans to support libssh. Until such time, there is not much to do here.

**Comment by toddr** [comment]
Thanks for the info. Opened https://github.com/libgit2/libgit2/issues/5225.
