### ISSUE TITLE
Git::Raw::Graph()->is_descendant_of doesn't propagate error codes

### ISSUE THREAD

**Issue by danzimm** [jacquesg/p5-Git-Raw#217]
If there's an error trying to determine if a commit is descendant of another then the error code is returned rather than "die"-ing with the error. In effect it's easy to write buggy code:
```
if (Git::Raw::Repo->is_descendant_of($repo, $commit, $ancestor)) {
 # this will get called even if there's an error
}
```

Under the hood it turns out `git_graph_descendant_of` will return a negative number if there's an error (and Git::Raw returns that value directly). Naturally my workaround is to ensure the result is `> 0` instead of just checking truthiness.

**Comment by jacquesg** [comment]
Thank you for the bug report, fixed in af44db71e6fc5abdf4beffd07faf402a817bfac9
