### ISSUE TITLE
Compilation error on FreeBSD systems (0.30-TRIAL)

### ISSUE THREAD

**Issue by eserte** [jacquesg/p5-Git-Raw#49]
Compilation fails on FreeBSD systems:

```
 xs/libgit2/include/git2/transport.h:15:21: error: libssh2.h: No such file or directory
```

libssh2 is installed and the check_lib check before was apparently successful. Problem is that 3rd party libraries are install to /usr/local on *BSD systems, and probably Makefile.PL does not address this.

Regards, Slaven

**Comment by rwp0** [comment]
is [openbsd](https://www.openbsd.org/) not supported? ([libgit](https://openports.se/devel/libgit2/libgit2) is ported)
it might require similar changes as freebsd in [makemaker.pm](https://github.com/jacquesg/p5-Git-Raw/blob/master/inc/MakeMaker.pm)
(eg. '/usr/local/' for `inc` and `lib`)

output on `use Git::Raw;`:
`
perl:/usr/local/libdata/perl5/site_perl/amd64-openbsd/auto/Git/Raw/Raw.so: undefined symbol 'libssh2_init'

ld.so: perl: lazy binding failed!
`

**Comment by jacquesg** [comment]
You seem to be missing libssh2
